name: Rust
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: tests
      run: cargo test expand_compare
