name: Rust fmt build test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always
jobs:
  all:
    name: all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: cargo fmt -- --check
      - name: build
        run: cargo build
      - name: install
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-expand
          version: latest
      - name: expand
        run: cargo expand --example example_01
      - name: test
        run: cargo test test_01_expand_compare
